import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'
import LocalFont from 'next/font/local'
import { NextFontWithVariable } from "next/dist/compiled/@next/font";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const editorial: NextFontWithVariable = LocalFont({
  src: [
    {
      path: './fonts/PPEditorialNew-Regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-editorial',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${editorial.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
